# Generated by Django 6.0.2 on 2026-02-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_gamesession_current_question_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebriefSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debrief_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('validation_status', models.CharField(default='pass', max_length=32)),
                ('error_log', models.JSONField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debrief_snapshot', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('difficulty', models.PositiveIntegerField(default=3)),
                ('seed', models.IntegerField()),
                ('scenario_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('validation_status', models.CharField(default='pass', max_length=32)),
                ('error_log', models.JSONField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_snapshot', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='StageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prepare', 'Prepare'), ('detect', 'Detect'), ('analyse', 'Analyse'), ('remediate', 'Remediate'), ('post_incident', 'Post-Incident')], max_length=30)),
                ('inject_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('validation_status', models.CharField(default='pass', max_length=32)),
                ('error_log', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_snapshots', to='gameplay.gamesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'stage'), name='unique_stage_snapshot_per_session')],
            },
        ),
    ]
