# Generated by Django 6.0.2 on 2026-02-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_gamesession_difficulty_gamesession_pressure_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('stage', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('slug', 'difficulty', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('phase', models.CharField(choices=[('Prepare', 'Prepare'), ('Detect', 'Detect'), ('Analyse', 'Analyse'), ('Remediation', 'Remediation'), ('Post-Incident', 'Post-Incident')], max_length=20)),
                ('prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('delta_score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gameplay.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['playbook', 'phase'], name='gameplay_qu_playboo_8f5da9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['external_id'], name='gameplay_qu_externa_e17ac2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'label')},
        ),
    ]
